//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDrivenBot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question : Step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.ResponseOptions = new HashSet<ResponseOption>();
        }
    
        public string Prompt { get; set; }
        public string RetryPrompt { get; set; }
        public int ResponseTypeID { get; set; }
    
        public virtual ResponseType ResponseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseOption> ResponseOptions { get; set; }
    }
}
