//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDrivenBot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCall : Step
    {
        public string URL { get; set; }
        public string Method { get; set; }
        public string Headers { get; set; }
    }
}
