//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDrivenBot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int ID { get; set; }
        public Nullable<int> NextStepID { get; set; }
        public Nullable<int> PayloadPropertyID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ConversationID { get; set; }
        public Nullable<bool> StartingStep { get; set; }
    
        public virtual PayloadProperty PayloadProperty { get; set; }
        public virtual Step NextStep { get; set; }
        public virtual ConversationTemplate ConversationTemplate { get; set; }
    }
}
